web_monitor/monitoring_board/urls.py
from django.conf.urls import url

from . import views

app_name = 'monitoring_board'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^pages/(?P<contact_id>[0-9]+)$', views.pages, name='pages'),
    url(r'^add/contact$', views.addContact, name='add_contact'),
    url(r'^add/page$', views.addPage, name='add_page'),
]

web_monitor/web_monitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('monitoring_board.urls')),
]

web_monitor/monitoring_board/models.py
from __future__ import unicode_literals

from django.db import models


class Contact(models.Model):
    email = models.EmailField(max_length=200, unique=True)
    name = models.CharField(max_length=500)

    def __str__(self):
        return "Contact(" + str(self.id) + "," + self.name + "," + self.email + ")"


class Page(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)
    url = models.CharField(max_length=500)
    date = models.DateTimeField()

    def __str__(self):
        return "Page(" + self.url + "," + str(self.date) + ")"

web_monitor/monitoring_board/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.CharField(max_length=200)
    name = forms.CharField(max_length=500)
    urls = forms.CharField()
    dates = forms.CharField()


class PageForm(forms.Form):
    contact_id = forms.IntegerField()
    url = forms.CharField(max_length=200)
    date = forms.DateTimeField()

web_monitor/monitoring_board/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from .forms import ContactForm, PageForm
from django.views.decorators.csrf import csrf_exempt

from .models import Contact, Page


def index(request):
    contact_list = Contact.objects.order_by('name')
    return render(request, 'monitoring_board/contacts.html',
                  {'active_contacts': True, 'contact_list': contact_list})


def pages(request, contact_id):
    page_list = Page.objects.filter(contact=contact_id).order_by('-date')
    return render(request, 'monitoring_board/pages.html',
                  {'active_pages': True, 'page_list': page_list, 'contact_id': contact_id})


@csrf_exempt
def addContact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            name = form.cleaned_data.get('name')
            urls = form.cleaned_data.get('urls').split(',')
            dates = form.cleaned_data.get('dates').split(',')
            contacts = Contact.objects.filter(email=email)
            contact = None
            if contacts:
                contact = contacts[0]
            else:
                contact = Contact(email=email, name=name)
                contact.save()

            currentURL = None
            if len(urls) == len(dates):
                for i in range(len(urls)):
                    currentURL = urls[i]
                    newPage = Page(contact=contact, url=currentURL, date=dates[i])
                    newPage.save()

            return redirect(currentURL[:-2] + '/0/' + str(contact.id))
        else:
            return HttpResponse("Invalid contact form!")


@csrf_exempt
def addPage(request):
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            contact_id = form.cleaned_data.get('contact_id')
            url = form.cleaned_data.get('url')
            date = form.cleaned_data.get('date')
            contact = get_object_or_404(Contact, pk=contact_id)
            newPage = Page(contact=contact, url=url, date=date)
            newPage.save()
            red = redirect(url[:-2] + "/0")
            print(red)
            return red
        else:
            return HttpResponse("Invalid page form!")

web_monitor/monitoring_board/templates/monitoring_board/contacts.html
{% extends 'monitoring_board/base.html' %}
{% load staticfiles %}

{% block table_title %}
    Contacts
{% endblock %}

{% block table_columns %}
    <th width="130px">Contact ID</th>
    <th>Name</th>
    <th>E-mail</th>
{% endblock %}


{% block table_content %}
    {% for contact in contact_list %}
        <tr>
            <td><a href="{% url 'monitoring_board:pages' contact.id %}">{{ contact.id }}</a></td>
            <td>{{ contact.name }}</td>
            <td>{{ contact.email }}</td>
        </tr>
    {% endfor %}
{% endblock %}

web_monitor/monitoring_board/templates/monitoring_board/pages.html
{% extends 'monitoring_board/base.html' %}
{% load staticfiles %}

{% block table_title %}
    Web Pages of the Contact {{ contact_id }}
{% endblock %}

{% block table_columns %}
    <th width="130px">Page ID</th>
    <th>URL</th>
    <th>Date</th>
{% endblock %}

{% block table_content %}
    {% for page in page_list %}
        <tr>
            <td>{{ page.id }}</td>
            <td><a href="{{ page.url }}" target="_blank">{{ page.url }}</a></td>
            <td>{{ page.date }}</td>
        </tr>
    {% endfor %}
{% endblock %}

web_monitor/templates/monitoring_board/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'monitoring_board/images/favicon.ico' %}">

    <title>WebMonitor</title>

    <!-- Bootstrap core CSS -->


    <!-- Custom styles for this template -->
    <link href="{% static 'monitoring_board/dashboard.css' %}" rel="stylesheet">
</head>

<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">WebMonitor</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse"
                data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</header>

<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link {% if active_contacts %}active{% endif %}" href="/">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active_pages %}active{% endif %}" href="#">Web Pages</a>
                </li>
            </ul>
        </nav>

        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
            <h2>
                {% block table_title %}
                {% endblock %}
            </h2>
            <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            {% block table_columns %}
                            {% endblock %}
                        </tr>
                        </thead>
                        <tbody>
                        {% block table_content %}
                        {% endblock %}
                        </tbody>
                    </table>
            </div>
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
      integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>
</html>